name: Node.js Package
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: Prepare Packages
        run: |
          yarn
          yarn build
          cp README.md packages/builder/README.md
          cp logo.png packages/builder/
          cp logo.png packages/core/
      - name: Publish @angular/builder
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd packages/builder && npm publish --access public
      - name: Publish @angular/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd packages/core/dist && npm publish --access public
